- name: Copy MongoDB YUM repo file
  ansible.builtin.template:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB Client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

#- name: Load Schema
#  community.mongodb.mongodb_shell:
#    login_host: "{{ lookup('aws_ssm', 'param.{{ENV}}.catalogue.MONGO_ENDPOINT', region='us-east-1' ) }}"
#    file: "{{APP_LOC}}/schema/{{COMPONENT}}.js"
#    idempotent: yes

- name: Load Schema
  ansible.builtin.shell: mongo --host dev-mongodb.devops321.online </"{{APP_LOC}}"/schema/{{COMPONENT}}.js
  login_host: "{{ lookup('aws_ssm', 'param.{{ENV}}.catalogue.MONGO_ENDPOINT', region='us-east-1' ) }}"
  idempotent: yes



