- name: load schema
  community.mongodb.mongodb_shell:
    login_host: "{{ lookup('aws_ssm', 'param.{{ENV}}.catalogue.MONGO_ENDPOINT', region='us-east-1' ) }}"
    file: "/path/to/mongo/file.js"
    idempotent: yes
  loop:
      - catalogue
      - users