
#    PRINT "Configure Endpoints for SystemD Configuration"
#    sed -i -e 's/MONGO_DNSNAME/dev-mongodb.devops321.online/' -e 's/REDIS_ENDPOINT/dev-redis.devops321.online/' -e 's/CATALOGUE_ENDPOINT/dev-catalogue.devops321.online/' -e 's/MONGO_ENDPOINT/dev-mongodb.devops321.online/' -e 's/CARTENDPOINT/dev-cart.devops321.online/' -e 's/DBHOST/dev-mysql.devops321.online/' -e 's/AMQPHOST/dev-rabbitmq.devops321.online/' -e 's/CARTHOST/dev-cart.devops321.online/' -e 's/USERHOST/dev-user.devops321.online/' /home/roboshop/${COMPONENT}/systemd.service &>>$LOG
#
#    mv /home/roboshop/${COMPONENT}/systemd.service /etc/systemd/system/${COMPONENT}.service
#    STAT $?
#
#    PRINT "Restart ${COMPONENT}"
#    systemctl daemon-reload &>>$LOG && systemctl restart ${COMPONENT} &>>$LOG && systemctl enable ${COMPONENT} &>>$LOG


- name: Setup SystemD service File
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/{{ COMPONENT }}.service

- name: Start {{ COMPONENT }} service
  ansible.builtin.systemd:
    name: "{{  COMPONENT  }}"
    state: restarted
    enabled: yes
    daemon-reload: yes
